# permissions for end users to view ansiblejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansiblejob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: awx-resource-go-operator
    app.kubernetes.io/part-of: awx-resource-go-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansiblejob-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - ansiblejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - ansiblejobs/status
  verbs:
  - get
